import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import BaseLayout from "@/components/layouts/BaseLayout";
import Footer from "@/components/layouts/Footer";
import Navigation from "@/components/layouts/navigation";

const NotoSansJP = Noto_Sans_JP({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daichi904",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${NotoSansJP.className} antialiased bg-gradient-to-r from-purple-50 via-slate-50 to-purple-50 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900`}
      >
        <BaseLayout>
          <Navigation />
          {children}
          <Footer />
        </BaseLayout>
      </body>
    </html>
  );
}
